version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "443:80"
  wordpress:
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
  marinadb:
    build:
      context: .
      dockerfile: ./requirements/marinadb/Dockerfile
